[package]
name = "twitchbot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitchchat = { version = "0.14", features = ["async", "smol"] }
smol = "1.2.5"
anyhow = "1.0.44"